exports.mongodbconfig={
    url:'mongodb://139.129.97.1:27017',
    databaseName:{
        firstdemo:"firstdemo",
        mydata:"mydata"
    },
    collection:{
        firstdemo:{
            user:"user",
            documents:"documents"
        }
    }
}
